## SENTIMENT ANALYSIS USING LSTM

In [4]:
import pandas as pd
tamil_train_data = pd.read_csv("tamil_train.tsv_cleaned.csv")
tamil_val_data = pd.read_csv("tamil_dev.tsv_cleaned.csv")
tamil_test_data = pd.read_csv("tamil_test.tsv_cleaned.csv")

In [5]:
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences

max_features = 1500
tokenizer = Tokenizer(num_words=max_features, split=' ')
tokenizer.fit_on_texts(tamil_train_data['text'].values)


In [6]:

X_train = tokenizer.texts_to_sequences(tamil_train_data['text'].values)
X_train = pad_sequences(X_train)
print(X_train[:2])
print(len(X_train))

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    5  742   14 1214    2
    55]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0 1215  256  281    5
   217]]
10967


In [7]:
Y_train = pd.get_dummies(tamil_train_data['category']).values
print(Y_train)
len(Y_train)

[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]]


10967

In [8]:
X_val = tokenizer.texts_to_sequences(tamil_val_data['text'].values)
X_val = pad_sequences(X_val)

In [9]:
Y_val = pd.get_dummies(tamil_val_data['category']).values
Y_test = pd.get_dummies(tamil_test_data['category']).values

In [10]:
X_test = tokenizer.texts_to_sequences(tamil_test_data['text'].values)
X_test = pad_sequences(X_test)

In [10]:
import pickle
# saving
with open('lstm_tokenizer.pkl', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [23]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Bidirectional , Dropout , LSTM

In [24]:
model = Sequential()
model.add(Embedding(max_features, 256))
model.add(Bidirectional(LSTM(128)))
model.add(Dense(128)) 
model.add(Dense(4,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop',metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 256)         384000    
                                                                 
 bidirectional (Bidirectiona  (None, 256)              394240    
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               32896     
                                                                 
 dense_1 (Dense)             (None, 4)                 516       
                                                                 
Total params: 811,652
Trainable params: 811,652
Non-trainable params: 0
_________________________________________________________________
None


2023-11-30 11:52:45.600022: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-11-30 11:52:45.601551: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-11-30 11:52:45.602216: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [11]:
print("X_train shape:", X_train.shape)
print("y_train shape:", Y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", Y_test.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", Y_val.shape)

X_train shape: (10967, 57)
y_train shape: (10967, 4)
X_test shape: (3049, 20)
y_test shape: (3049, 4)
X_val shape: (1231, 16)
y_val shape: (1231, 4)


In [ ]:
model.fit(X_train, Y_train, epochs = 1, batch_size= 32 ,verbose = 1 , validation_data=(X_val,Y_val))

In [27]:
import pickle
with open('llm_lstm_model_2.pkl', 'wb') as file:
    pickle.dump(model, file)

In [ ]:
model.save("llm_lstm_model_3")

In [ ]:
Y_pred = model2.predict(X_test)

In [14]:
Y_pred[:5]

array([[0.07841045, 0.09709293, 0.78189003, 0.04260656],
       [0.0773256 , 0.0517784 , 0.8157901 , 0.05510585],
       [0.07344203, 0.05634459, 0.8361154 , 0.03409794],
       [0.10368995, 0.16395472, 0.6861884 , 0.04616686],
       [0.07238767, 0.06516671, 0.81134963, 0.05109596]], dtype=float32)

In [15]:
classes = ['Mixed_feelings','Negative','Positive','unknown_state']

In [16]:
import numpy as np
pred_class = []
for item in Y_pred:
  index = np.argmax(item)
  pred_class.append(classes[index])
  #pred_class.append(index)

print(pred_class)

['Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Po

In [29]:
tokenizer.sequences_to_texts([X_test[304]])

['ennada vfx idhu ivlo cartoon madri irukku']

In [24]:
[(i, x)  for i, x in enumerate(pred_class) if x == "Negative"]

[(232, 'Negative'),
 (262, 'Negative'),
 (304, 'Negative'),
 (319, 'Negative'),
 (340, 'Negative'),
 (553, 'Negative'),
 (595, 'Negative'),
 (608, 'Negative'),
 (721, 'Negative'),
 (888, 'Negative'),
 (1004, 'Negative'),
 (1009, 'Negative'),
 (1017, 'Negative'),
 (1087, 'Negative'),
 (1119, 'Negative'),
 (1186, 'Negative'),
 (1213, 'Negative'),
 (1268, 'Negative'),
 (1277, 'Negative'),
 (1315, 'Negative'),
 (1389, 'Negative'),
 (1458, 'Negative'),
 (1586, 'Negative'),
 (1645, 'Negative'),
 (1741, 'Negative'),
 (1817, 'Negative'),
 (1933, 'Negative'),
 (1961, 'Negative'),
 (2105, 'Negative'),
 (2147, 'Negative'),
 (2148, 'Negative'),
 (2164, 'Negative'),
 (2188, 'Negative'),
 (2291, 'Negative'),
 (2303, 'Negative'),
 (2374, 'Negative'),
 (2432, 'Negative'),
 (2465, 'Negative'),
 (2531, 'Negative'),
 (2660, 'Negative'),
 (2709, 'Negative'),
 (2833, 'Negative'),
 (2847, 'Negative'),
 (2899, 'Negative'),
 (2999, 'Negative'),
 (3001, 'Negative')]

In [32]:
len(pred_class)

3049

In [33]:
print("\n Training Accuracy :" , model.evaluate(X_train, Y_train  , verbose = 2)[1] ,"\n")
print("\n Testing Accuracy :" , model.evaluate(X_test, Y_test , verbose = 2)[1] )

2023-11-30 11:53:47.660202: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-11-30 11:53:47.661332: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-11-30 11:53:47.662620: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

343/343 - 15s - loss: 0.8170 - accuracy: 0.7027 - 15s/epoch - 44ms/step

 Training Accuracy : 0.7026534080505371 

96/96 - 2s - loss: 0.8971 - accuracy: 0.6855 - 2s/epoch - 16ms/step

 Testing Accuracy : 0.6854706406593323


In [34]:
from sklearn.metrics import classification_report
print(classification_report(pred_class,tamil_test_data['category']))

                precision    recall  f1-score   support

Mixed_feelings       0.00      0.00      0.00         0
      Negative       0.06      0.54      0.11        46
      Positive       1.00      0.69      0.81      3003
 unknown_state       0.00      0.00      0.00         0

      accuracy                           0.69      3049
     macro avg       0.26      0.31      0.23      3049
  weighted avg       0.98      0.69      0.80      3049



/Users/deebakkarthi/.local/share/conda/envs/19CSE453/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/deebakkarthi/.local/share/conda/envs/19CSE453/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/deebakkarthi/.local/share/conda/envs/19CSE453/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [11]:
X_test[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0, 305, 484], dtype=int32)

In [ ]:
tmp = pad_sequences(tokenizer.texts_to_sequences(["thala mass"]))

In [1]:
import keras.models

In [ ]:
model2 = keras.models.load_model("./llm_lstm_model.keras/")

In [39]:
model2.predict(tmp)

2023-11-30 11:57:04.143883: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-11-30 11:57:04.145357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-11-30 11:57:04.147435: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

1/1 [==============================] - 0s 493ms/step


array([[0.07299575, 0.0295685 , 0.8820374 , 0.01539834]], dtype=float32)